### ISSUE TITLE
协议自动选择，可选配置db名

### ISSUE THREAD

**Issue by postor** [latel/logline#1]
建议：
1.indexdb优先，localstorage降级
2.可选配置db名，localstorage可降级前缀

理由：
websql已经标记弃用
indexdb明显更适用log但是支持浏览器受限
db名又是域名下全局性的东西，'logs'有可能别的东西也在用

**Comment by latel** [comment]
好的，感谢建议，下个小版本加上这些特性.
不想用的协议可以不用的，可以使用 `npm run configure -- --with-xxx` 来只打包自己需要的实现。

**Comment by latel** [comment]
指定数据库名：
``` javascript
Logline.using(日志协议, 自定义数据库名);
Logline.database(自定义数据库名)
```

如果没有使用using指明希望使用的协议名，则会自动按照优先级选择一个可用的协议，优先级来自打包时的参数顺序，默认的打包顺序是 'indexeddb,websql,localstorage'，可根据自己需要自行打包，参考README中的自定义构建部分。
