### ISSUE TITLE
能否支持日志集中管理？

### ISSUE THREAD

**Issue by Samli514006030** [latel/logline#4]
您好，

我想请问logline能否做到类似nodejs的log4js，将所有前台日志根据定义存储在不同文件夹中。

非常期待您的回复。

**Comment by latel** [comment]
H5存储木有文件夹的概念啊，现在常用的H5存储有webstorage, cookie, websql, indexeddb，都木有文件夹的概览。

logline职责只负责用户端的日志收集和存储，具体的分析有以下两种情况：
1. 开发时可以直接用现在非常成熟的远程调试功能实时的直接在开发电脑上看到手机上的日志。
2. 线上运行时，应该由业务方自己开发一套日志手机系统，将用户端的日志统一上报过去，然后落地到数据库或者其他地方。

我们有开发一整套流程的计划，但是还需要时间。

感谢你的支持 : )

**Comment by Samli514006030** [comment]
tks,非常感谢你的回复。
